version: '3.8'

services:
  postgres-db:
    image: postgres:15.13-alpine3.22
    container_name: shareit-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 11111
      POSTGRES_DB: shareitdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
