spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shareitdb
    username: user
    password: 11111
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      org.springframework.web: INFO
      org.hibernate: INFO
      root: INFO

