server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shareitdb
    username: user
    password: 11111
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  level:
    org.springframework: INFO
    ru.practicum.shareit: DEBUG
