-- USERS
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(255)  NOT NULL,
  email       VARCHAR(512)  NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS item_requests (
    id            BIGSERIAL PRIMARY KEY,
    description   TEXT      NOT NULL,
    requester_id  BIGINT    NOT NULL,
    created       TIMESTAMP NOT NULL,
    CONSTRAINT fk_request_user FOREIGN KEY(requester_id) REFERENCES users(id)
);
-- ITEMS
CREATE TABLE IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(255)  NOT NULL,
  description TEXT          NOT NULL,
  available   BOOLEAN       NOT NULL,
  owner_id    BIGINT        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  request_id  BIGINT,
  CONSTRAINT fk_item_request FOREIGN KEY (request_id) REFERENCES item_requests(id)
);

-- BOOKINGS
CREATE TABLE IF NOT EXISTS bookings (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id    BIGINT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  booker_id  BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  start_date TIMESTAMP NOT NULL,
  end_date   TIMESTAMP NOT NULL,
  status     VARCHAR(32) NOT NULL
);

-- COMMENTS
CREATE TABLE IF NOT EXISTS comments (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text       TEXT          NOT NULL,
  author_id  BIGINT        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  item_id    BIGINT        NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  created    TIMESTAMP     NOT NULL
);
